### ISSUE TITLE
Practica8Hilos_en_consola.

### ISSUE THREAD

**Issue by Aylin67** [SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-equipo_eaaj#1]
[practica7visual.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-equipo_eaaj/files/15113452/practica7visual.pdf)

**Comment by AricelCastro** [comment]
nuestro equipo le da un puntaje de 19/20 
ya que cumple con la rubrica pero faltan algunas imagenes

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
